version: "3.9"
services:
    poc-core-db:
        image: postgres:16
        environment:
            POSTGRES_USER: valtimo
            POSTGRES_PASSWORD: valtimo
        ports:
            - "15432:5432"

    poc-core-keycloak-db:
        image: mysql:8-oracle
        ports:
            - "3307:3306"
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        command:
            --connect-timeout=40000
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: password

    poc-core-keycloak:
        image: keycloak/keycloak:20.0
        ports:
            - "8082:8080"
        depends_on:
            - poc-core-keycloak-db
        environment:
            KC_HOSTNAME_URL: http://localhost:8082/auth/
            KC_HOSTNAME_ADMIN_URL: http://localhost:8082/auth/
            KC_HTTP_RELATIVE_PATH: "/auth/"
            KC_DB: mysql
            KC_DB_URL: jdbc:mysql://poc-core-keycloak-db:3306/keycloak?characterEncoding=UTF-8
            KC_DB_PASSWORD: password
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_HTTP_ENABLED: "true"
            KC_HEALTH_ENABLED: "true"
            KC_LOG_LEVEL: info
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8082/auth/health/ready" ]
            interval: 15s
            timeout: 2s
            retries: 15
        command: [ "start --import-realm" ]
        volumes:
            - ./docker/keycloak:/opt/keycloak/data/import/

    poc-rabbitmq:
        image: rabbitmq:3-management
        container_name: poc-rabbitmq
        volumes:
            - ./docker/imports/poc-rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
            - ./docker/imports/poc-rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
        ports:
            - "5672:5672"
            - "15672:15672"

volumes:
    poc-core-db-data: #enabled persistence
