spring:
    application:
        name: valtimo-backend-poc
    datasource:
        url: jdbc:postgresql://localhost:15432/postgres
        username: valtimo
        password: valtimo

valtimo:
    app:
        hostname: localhost:4200
    connector-encryption:
        secret: "0123456789101112"
    oauth:
        public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAooyECQIi6v4TLKOYWwXClDhJcrGcGfKZj7LQIgY/Ajm2nAKv5kiZRoS8GzMzIGKkkilAJyWQCoKlP//azHqzIxO6WZWCqGFxd04vK5JYujsiMMTNvTggfFSM7VxbzU/wv+aAEvBaGUMYp2Oamn5szzYzkzsowujvDZp+CE8ryZWTVmA+8WZE4aoU6VzfXmMDmPxvRXvktPRsJkA7hkv65TTJwUZF38goRg62kRD0hOP1sIy6vwKDSkjafLV1bYNBRiWXNReJNBXauhy74GeiHODGrI62NwUJXSgZ62cViPt6cx/3A7VBPLpEPnpnlZcIDfsFpSUuNEXc7HoLRuldbQIDAQAB

# ==================
# keycloak server to server config
# ==================
keycloak:
    realm: valtimo
    auth-server-url: http://localhost:8082/auth/
    resource: valtimo-user-m2m-client
    credentials:
        secret: 6ef6ca16-6b86-482a-a3d9-0561704c1db9